# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: mernauth
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  adminmongo: 
    image: mrvautin/adminmongo
    restart: always
    container_name: adminmongo
    ports: 
      - '12345:12345'
    environment:
      CONN_NAME: mern
      HOST: 0.0.0.0
      PORT: 12345
      DB_USERNAME: mernuser
      DB_PASSWORD: mernpass
      DB_NAME: mernauth
      DB_HOST: mongo
